### ISSUE TITLE
Why use `hid` ?

### ISSUE THREAD

**Issue by emdete** [mrmoss/minidx3#1]
Here the device shows up as a serial device:

```
Bus 001 Device 081: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port
```

which shows different IDs than mentioned in the program (0x0801, 0x0083). 

The PL2303 seems to be cantained in the USB-A plug already, the device itself seems to have a serial RS232 only. I wonder why you have those IDs, are there different Cables contained in the package? My device states "Version: V2015", maybe there are differences in the version?

HID doesnt work with serial so i try to convert everything to `python-serial` but the device doesnt answer.

Do you habe any hints?

**Comment by mrmoss** [comment]
This project is a blast from the past :joy: 

I recall sniffing the serial port, but I couldn't get anything out of it. The manual I have attached in this repo says the serial port can be used to upload new firmware, but I don't know if it actually implements any of the other functionality via the serial port.

All the effort to get this thing working was by sniffing serial/USB packets while running the sketchy software on the CD in a VM. As I recall, the software seemed to only use USB for interfacing with the device.

I'd try and help here, but I don't know if have this device anymore (I looked and cannot find it), so there's not much I can do on my end. :frowning_face:

If you have the firmware version you're running, and can get the corresponding firmware bin file, we could try to reverse it and see if there's any hidden functionality that the serial port has, but I'm guessing that's a lot more work than just sticking to USB packets. :wink:

**Comment by emdete** [comment]
You're right. Point is: My device has a serial (RS232) port only. My cable contains a PL2303 in the USB-A plug, i assume your's had a different cable with a different functionality in the plug which shows with the codes 0x0801,0x0083 as used in your program. I assume your model may be used to scan/read cards in realtime, not storing them. So it would simulate a HID to enter the codes like an keyboard?

Anyway i rewrote the protocol part and it works quite ok. The protocol differs in some aspects from the docu but hey. The device doesnt store all scans i do. So all in all it's a bit crappy. If you find your device it would be great to check if my code would work...

thanks & best regards, m.

**Comment by mrmoss** [comment]
My device stored them as well. As far as I remember, they were just using HID as a 1:1 replacement to serial to remove driver depenendencies (no serial driver needed, just use USB HID feature reports).

Glad you got it working! This was a one off project. Glad it was slightly useful to someone else! :smiley:
